FROM ubuntu

RUN apt update && apt install -y git \
    binutils \
    build-essential \
    gdb-multiarch \
    #gcc-arm-linux-gnueabi \
    #binutils-arm-linux-gnueabi \
    gcc-arm-linux-gnueabihf \
    gcc-9-aarch64-linux-gnu

WORKDIR /test
CMD ["tail", "-f", "/dev/null"]